[project]
name = "fabric-link"
version = "0.1.0"
description = "Provides middleware to connect and call a tool on a MCP server via JSON-RPC"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests",
]
